name: Lux Banker
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90415
title: Banking for HNWI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff6200'
    - '#a8a8a8'
    - '#27548d'
    - '#1f1f1f'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.9422159052919596
purpose: []
