name: Lux Banker
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.24230857659131289
  lightness: 0.5728730137925595
  saturation: 0.9514515260234475
  rhythmicContrast: 0.9422159052919596
purpose: []
